// <auto-generated />
using ExtremeVacation.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExtremeVacation.Api.Migrations
{
    [DbContext(typeof(ExtremeVacationDbContext))]
    [Migration("20230607112441_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExtremeVacation.Api.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("ExtremeVacation.Api.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("ExtremeVacation.Api.Entities.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ChanceOfSurvival")
                        .HasColumnType("int");

                    b.Property<string>("Danger")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Trips");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            ChanceOfSurvival = 70,
                            Danger = "terrorist attacks",
                            Description = "Wanna spend some time in a city where terrorists strike on a daily basis? Then this place is for you. You will be staying in one of the old tenement houses downtown, right where the most attacks happen. You're not advised to leave your room during your stay.",
                            Destination = "an island on the Atlantic Ocean",
                            Duration = 6,
                            ImageURL = "/images/city/apocalyptic.jpg",
                            Name = "Under Fire",
                            Price = 320m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            ChanceOfSurvival = 99,
                            Danger = "extreme noise",
                            Description = "It tolls for thee. At least it may toll for you if you would like to spend your vacation in a campanile. You will be staying in a tall tower with a couple bells. The bells will be ringing every hour and it will actually be your task to ring them. Gonna be loud.",
                            Destination = "Sicily",
                            Duration = 4,
                            ImageURL = "/images/city/campanile.jpg",
                            Name = "For Whom Does the Bell Toll?",
                            Price = 190m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            ChanceOfSurvival = 90,
                            Danger = "collapse",
                            Description = "Here's an opportunity for you to spend some time in a building that is being demolished. One part of the building is still standing and will not be touched as long as you stay there. The question is, is the remaining part going to collapse or not? You will never know until you try.",
                            Destination = "Detroit",
                            Duration = 4,
                            ImageURL = "/images/city/demolished.jpg",
                            Name = "Is it Gonna Collapse?",
                            Price = 470m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            ChanceOfSurvival = 30,
                            Danger = "strong wind",
                            Description = "Who wouldn't like to laze in a hammock? Except the hammock is stretched between two skyscrapers and you must figure it out yourself how to get to it. But when you finally manage to get to it, you will be able to relax and admire the beautiful view of the city. Hopefully, it's not gonna be too windy.",
                            Destination = "New York",
                            Duration = 3,
                            ImageURL = "/images/city/hammock.jpg",
                            Name = "Chill Out in a Hammock",
                            Price = 760m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            ChanceOfSurvival = 2,
                            Danger = "your cellmate",
                            Description = "Would you like to know what it feels like to be a prisoner? Here you have a great opportunity to become one, at least for a limited period of time. You will be ding the same stuff as all the real prisoners, you will get the same food, and, what's even better, you will be in one cell with the most dangerous serial killer.",
                            Destination = "Northern Europe",
                            Duration = 14,
                            ImageURL = "/images/city/prison.jpg",
                            Name = "Behind Bars",
                            Price = 960m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            ChanceOfSurvival = 40,
                            Danger = "falling down",
                            Description = "Why not spend your vacation in the Alps? You will be staying on top of a very steep rock. The bathroom is on another steep rock and there's a five-meter gap between the two rocks, so each time you want to use the bathroom, you have to jump from one rock to the other and then back. But it shouldn't be a big deal, right?",
                            Destination = "the Alps",
                            Duration = 5,
                            ImageURL = "/images/mountains/steep.jpg",
                            Name = "For Good Jumpers Only",
                            Price = 270m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            ChanceOfSurvival = 10,
                            Danger = "hot lava",
                            Description = "If you don't like crowded places, this little island is for you. There is magma right below the surface and the rocks melt every couple days. If you like being surrounded by hot lava, this destination is for you. Just remember to climb the peaks of the rocks when the rock melts. They're less hot than the other parts.",
                            Destination = "off the shores of Indonesia",
                            Duration = 4,
                            ImageURL = "/images/mountains/lava.jpg",
                            Name = "Molten Rock",
                            Price = 500m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            ChanceOfSurvival = 1,
                            Danger = "being eaten by wolves",
                            Description = "Do you like animals? If so, why not spend your vacation in the woods of the Scandinavian Mountains? You will join a pack of wolves and live like they do. You will be hunting together, they will teach you to howl, just make sure they're never hungry because this is when most tourists become their dinner.",
                            Destination = "Norway",
                            Duration = 8,
                            ImageURL = "/images/mountains/wolves.jpg",
                            Name = "Dances with Wolves",
                            Price = 720m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            ChanceOfSurvival = 1,
                            Danger = "being killed by the bear",
                            Description = "If you're thinking about spending your vacation in the Carpathian Mountains, you don't have to spend much money. You will be staying in the forest and sharing a den with a bear. You can play together or just hang out. Just two things to keep in mind: make sure the bear is never hungry and don't touch her cubs.",
                            Destination = "Southern Poland",
                            Duration = 5,
                            ImageURL = "/images/mountains/bear.jpg",
                            Name = "Den Sharing",
                            Price = 160m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            ChanceOfSurvival = 60,
                            Danger = "drowning",
                            Description = "You can spend your vacation in one of the caves situated on an island off the shores of Australia. The cave isn't very large and it gets completely filled with water when there is high tide, so you will have to be swimming all the time to keep above water. During low tide, though, you will be able to spend some nice time on a narrow beach.",
                            Destination = "Southern Pacific",
                            Duration = 10,
                            ImageURL = "/images/seaside/cave.jpg",
                            Name = "High Tide Cave",
                            Price = 640m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            ChanceOfSurvival = 70,
                            Danger = "suffocation",
                            Description = "There's an island near Japan where you can spend your vacation inhaling the sulforous fumes of a volcano. Don't worry, the volcano hasn't erupted for centuries now, but the sulfurous odor can be smelled all the time. Just don't breathe in too deep. If you catch some fish, you can try to smoke it over the crater.",
                            Destination = "off the shores of Japan",
                            Duration = 3,
                            ImageURL = "/images/seaside/volcano.jpg",
                            Name = "Volcanic Island",
                            Price = 450m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            ChanceOfSurvival = 30,
                            Danger = "disappearing along with the ship",
                            Description = "There is a ship that appears every now and then on the waters of the Bermuda Triangle. There's no one on board, but the tables are set and the tea is still hot, just as if the ship had been abandoned a couple minutes before. Unfortunately no one knows exactly when the ship will disappear again and what will happen to the passengers.",
                            Destination = "the Bermuda Triangle",
                            Duration = 2,
                            ImageURL = "/images/seaside/ship.jpg",
                            Name = "Ghost Ship",
                            Price = 980m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            ChanceOfSurvival = 50,
                            Danger = "being scared to death",
                            Description = "If you want to spend your vacation away from people, why don't you choose this beautiful house in the middle of an abandoned graveyard. The house isn't too cozy, but for that price? You should also know it's haunted, but the ghosts aren't very aggressive. They look really scary, though, so just don't look at them.",
                            Destination = "Scotland",
                            Duration = 7,
                            ImageURL = "/images/horror/haunted.jpg",
                            Name = "Haunted House",
                            Price = 120m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 4,
                            ChanceOfSurvival = 80,
                            Danger = "heart attack",
                            Description = "If you feel like spending some time in an abominable place, you can stay in a secret hospital. Terrible experiments on humans were carried out there in the 19th century and the ghosts of those who died there can still be seen from time to time, but these are just dreadful visions, not a real thing. Although they do look and feel real, so you'd better have a healthy heart.",
                            Destination = "a secret hospital in a secret location",
                            Duration = 5,
                            ImageURL = "/images/horror/ghost.jpg",
                            Name = "Just Visions",
                            Price = 520m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            ChanceOfSurvival = 50,
                            Danger = "falling down in the elevator",
                            Description = "This place has been kept secret for too long, but now you can not only visit it, but also stay in it for a couple days. The place is hidden under the ground and the only way to get there is by using an old elevator. The elevator is very noisy and you never know when it comes. Also, when you're in it, strange noises can heard and the lights start flickering. The elevator rope doesn't break every time, so you may be lucky.",
                            Destination = "Germany",
                            Duration = 3,
                            ImageURL = "/images/horror/abandoned.jpg",
                            Name = "The Elevator",
                            Price = 450m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            ChanceOfSurvival = 99,
                            Danger = "being bitten by the werewolf",
                            Description = "If you like history, this destination is for you. There are graves from the 17th century and beautiful tombs. You will find tons of information about the people who were buried there. And yes, there may be a werewolf roaming the place from time to time, but usually only at night. Just try to avoid him. He won't kill you, but if he bites you, you will turn into werewolf yourself. Is it really something you need?",
                            Destination = "Peru",
                            Duration = 8,
                            ImageURL = "/images/horror/werewolf.jpg",
                            Name = "Old Graveyard",
                            Price = 750m
                        });
                });

            modelBuilder.Entity("ExtremeVacation.Api.Entities.TripCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TripCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "City Vacation"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mountains Vacation"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Seaside Vacation"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Horror Vacation"
                        });
                });

            modelBuilder.Entity("ExtremeVacation.Api.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserName = "Annie"
                        },
                        new
                        {
                            Id = 2,
                            UserName = "Joe"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
